import type { CatalogDimension, UserMatrix } from "@/lib/types";

export const CATALOG_VERSION = "1.0.0";

export const SCHOOL_AREA_OPTIONS = [
  "Bloomingdale HS",
  "Newsome HS",
  "Riverview HS",
  "FishHawk / Lithia",
  "River Hills",
  "Other Hillsborough",
] as const;

export const CATALOG: CatalogDimension[] = [
  {
    id: "beds",
    cluster: "must_haves",
    defaultLabel: "Bedrooms",
    description: "Minimum bedroom count. Default preference is 4.",
    requiredFields: ["beds"],
    enrichable: false,
    defaultEnabled: true,
    defaultWeight: 8,
    defaultKnobs: { enabled: true, weight: 8, min: 4, mustHave: true },
    allowedKnobs: ["enabled", "weight", "min", "mustHave", "label"],
  },
  {
    id: "baths",
    cluster: "must_haves",
    defaultLabel: "Bathrooms",
    description: "Minimum bathroom count.",
    requiredFields: ["baths"],
    enrichable: false,
    defaultEnabled: true,
    defaultWeight: 4,
    defaultKnobs: { enabled: true, weight: 4, min: 2 },
    allowedKnobs: ["enabled", "weight", "min", "mustHave", "label"],
  },
  {
    id: "sqft",
    cluster: "must_haves",
    defaultLabel: "Living square feet",
    description: "Minimum heated living area. 2500 is a preference, not a global rule.",
    requiredFields: ["sqft"],
    enrichable: false,
    defaultEnabled: true,
    defaultWeight: 10,
    defaultKnobs: { enabled: true, weight: 10, min: 2500, mustHave: false },
    allowedKnobs: ["enabled", "weight", "min", "mustHave", "label"],
  },
  {
    id: "construction",
    cluster: "structure",
    defaultLabel: "Construction (block vs frame)",
    description: "Prefers concrete block over wood frame.",
    requiredFields: ["facts.construction"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 14,
    defaultKnobs: {
      enabled: true,
      weight: 14,
      mustHave: false,
      prefs: { prefer: "block" },
    },
    allowedKnobs: ["enabled", "weight", "mustHave", "label", "prefs"],
  },
  {
    id: "stories",
    cluster: "structure",
    defaultLabel: "Stories",
    description: "Prefer single-story unless you say otherwise.",
    requiredFields: ["facts.stories"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 4,
    defaultKnobs: { enabled: true, weight: 4, max: 1 },
    allowedKnobs: ["enabled", "weight", "max", "min", "label"],
  },
  {
    id: "roof_age",
    cluster: "structure",
    defaultLabel: "Roof age",
    description: "Newer roofs score higher. Default target is under 10 years.",
    requiredFields: ["facts.roofAgeYears"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 12,
    defaultKnobs: { enabled: true, weight: 12, max: 10, mustHave: false },
    allowedKnobs: ["enabled", "weight", "max", "mustHave", "label"],
  },
  {
    id: "hvac_age",
    cluster: "structure",
    defaultLabel: "HVAC age",
    description: "Newer HVAC scores higher.",
    requiredFields: ["facts.hvacAgeYears"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 8,
    defaultKnobs: { enabled: true, weight: 8, max: 10 },
    allowedKnobs: ["enabled", "weight", "max", "mustHave", "label"],
  },
  {
    id: "impact_glass",
    cluster: "structure",
    defaultLabel: "Impact glass / shutters",
    description: "Impact windows or shutters for Florida wind.",
    requiredFields: ["facts.impactGlass"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 8,
    defaultKnobs: { enabled: true, weight: 8, mustHave: false },
    allowedKnobs: ["enabled", "weight", "mustHave", "label"],
  },
  {
    id: "permits",
    cluster: "structure",
    defaultLabel: "Closed permits",
    description: "Major work (roof/HVAC/windows) permitted and closed.",
    requiredFields: ["facts.permitsClosed"],
    enrichable: true,
    defaultEnabled: false,
    defaultWeight: 4,
    defaultKnobs: { enabled: false, weight: 4 },
    allowedKnobs: ["enabled", "weight", "mustHave", "label"],
  },
  {
    id: "dom",
    cluster: "motivation",
    defaultLabel: "Days on market",
    description: "Longer DOM suggests more seller motivation.",
    requiredFields: ["daysOnMarket"],
    enrichable: false,
    defaultEnabled: true,
    defaultWeight: 8,
    defaultKnobs: { enabled: true, weight: 8, min: 30 },
    allowedKnobs: ["enabled", "weight", "min", "invert", "label"],
  },
  {
    id: "price_cuts",
    cluster: "motivation",
    defaultLabel: "Price cuts",
    description: "More list-price cuts suggest flexibility.",
    requiredFields: ["facts.priceCutCount"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 6,
    defaultKnobs: { enabled: true, weight: 6, min: 1 },
    allowedKnobs: ["enabled", "weight", "min", "label"],
  },
  {
    id: "failed_pending",
    cluster: "motivation",
    defaultLabel: "Failed pending / kick-out",
    description: "A failed pending can mean a motivated relist.",
    requiredFields: ["facts.failedPending"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 5,
    defaultKnobs: { enabled: true, weight: 5 },
    allowedKnobs: ["enabled", "weight", "label"],
  },
  {
    id: "list_vs_jv",
    cluster: "motivation",
    defaultLabel: "List vs county just value",
    description: "List at or below Hillsborough just value scores as better value / possible distress.",
    requiredFields: ["listPrice", "facts.countyJustValue"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 8,
    defaultKnobs: { enabled: true, weight: 8 },
    allowedKnobs: ["enabled", "weight", "label"],
  },
  {
    id: "price_cap",
    cluster: "money",
    defaultLabel: "List price vs budget",
    description: "How the ask compares to your max purchase price.",
    requiredFields: ["listPrice"],
    enrichable: false,
    defaultEnabled: true,
    defaultWeight: 10,
    defaultKnobs: { enabled: true, weight: 10, mustHave: true },
    allowedKnobs: ["enabled", "weight", "mustHave", "label"],
  },
  {
    id: "pitia_slack",
    cluster: "money",
    defaultLabel: "PITIA / monthly slack",
    description: "Estimated principal, interest, taxes, insurance vs your max payment and slack target.",
    requiredFields: ["listPrice"],
    enrichable: false,
    defaultEnabled: true,
    defaultWeight: 12,
    defaultKnobs: { enabled: true, weight: 12, mustHave: false },
    allowedKnobs: ["enabled", "weight", "mustHave", "label"],
  },
  {
    id: "school_area",
    cluster: "location",
    defaultLabel: "School / neighborhood area",
    description: "Match against your allowlist (Bloomingdale HS, River Hills, FishHawk, etc.).",
    requiredFields: ["facts.schoolArea"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 10,
    defaultKnobs: { enabled: true, weight: 10, mustHave: false },
    allowedKnobs: ["enabled", "weight", "mustHave", "label"],
  },
  {
    id: "hoa_cdd",
    cluster: "location",
    defaultLabel: "HOA / CDD",
    description: "Penalty if HOA or CDD is present and you asked to avoid them.",
    requiredFields: ["facts.hoa", "facts.cdd"],
    enrichable: true,
    defaultEnabled: true,
    defaultWeight: 4,
    defaultKnobs: {
      enabled: true,
      weight: 4,
      prefs: { avoidHoa: false, avoidCdd: false },
    },
    allowedKnobs: ["enabled", "weight", "mustHave", "label", "prefs"],
  },
  {
    id: "seller_credit",
    cluster: "deal",
    defaultLabel: "Seller credit vs price cut",
    description: "Informational preference: closing credit can beat a sticker cut at low down payment.",
    requiredFields: ["facts.sellerCreditPreferred"],
    enrichable: true,
    defaultEnabled: false,
    defaultWeight: 2,
    defaultKnobs: { enabled: false, weight: 2 },
    allowedKnobs: ["enabled", "weight", "label"],
  },
];

export function catalogById(id: string): CatalogDimension | undefined {
  return CATALOG.find((d) => d.id === id);
}

export function defaultMatrix(): UserMatrix {
  const dimensions: UserMatrix["dimensions"] = {};
  for (const dim of CATALOG) {
    dimensions[dim.id] = { ...dim.defaultKnobs, prefs: dim.defaultKnobs.prefs };
  }
  return {
    catalogVersion: CATALOG_VERSION,
    unknownPolicy: "skip",
    budget: {
      maxPrice: 550000,
      maxPitia: 3800,
      minMonthlySlack: 1000,
      downPaymentPct: 5,
      ratePct: 6.5,
      taxRatePct: 1.1,
      insuranceMonthly: 250,
    },
    locationAllowlist: ["Bloomingdale HS", "River Hills", "FishHawk / Lithia"],
    dimensions,
    manualRubrics: [],
  };
}

export function publicCatalog() {
  return CATALOG.map((d) => ({
    id: d.id,
    cluster: d.cluster,
    defaultLabel: d.defaultLabel,
    description: d.description,
    enrichable: d.enrichable,
    defaultEnabled: d.defaultEnabled,
    defaultWeight: d.defaultWeight,
    allowedKnobs: d.allowedKnobs,
  }));
}
